### ISSUE TITLE
test e7 fails sporadically

### ISSUE THREAD

**Issue by swachter** [wi101/elevator-system#1]
##teamcity[testFailed name='`run` must run all pick-up requests' message='|n- ElevatorState(15,Set())|n+ ElevatorState(1,Set())|n- ElevatorState(14,Set())|n+ ElevatorState(15,Set())|n' details='java.lang.Exception: |n- ElevatorState(15,Set())|n+ ElevatorState(1,Set())|n- ElevatorState(14,Set())|n+ ElevatorState(15,Set())|n|n	at org.specs2.matcher.MatchResultStackTrace.setStacktrace(Expectations.scala:57)|n	at org.specs2.matcher.MatchResultStackTrace.setStacktrace$(Expectations.scala:55)|n	at org.specs2.Specification.setStacktrace(Specification.scala:19)|n	at org.specs2.matcher.ExpectationsCreation.checkFailure(Expectations.scala:37)|n	at org.specs2.matcher.ExpectationsCreation.checkFailure$(Expectations.scala:36)|n	at org.specs2.Specification.checkFailure(Specification.scala:19)|n	at org.specs2.matcher.MustExpectationsCreation$$anon$2.check(MustExpectations.scala:29)|n	at org.specs2.matcher.Expectable.applyMatcher(Expectable.scala:51)|n	at org.specs2.matcher.MustExpectable.must_$eq$eq$eq(MustExpectable.scala:20)|n	at com.elevator.ElevatorSystemSpec.$anonfun$e7$8(ElevatorSystemSpec.scala:124)|n	at scalaz.zio.IO.$anonfun$map$2(IO.scala:66)|n	at scalaz.zio.RTS$.nextInstr(RTS.scala:123)|n	at scalaz.zio.RTS$FiberContext.evaluate(RTS.scala:389)|n	at scalaz.zio.RTS$FiberContext.resumeEvaluate(RTS.scala:654)|n	at scalaz.zio.RTS$FiberContext.resumeAsync(RTS.scala:672)|n	at scalaz.zio.RTS$FiberContext.$anonfun$evaluate$4(RTS.scala:450)|n	at scalaz.zio.RTS$FiberContext.$anonfun$evaluate$4$adapted(RTS.scala:450)|n	at scalaz.zio.RTS$FiberContext.$anonfun$evaluate$8(RTS.scala:539)|n	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)|n	at scalaz.zio.RTS$$anon$1.run(RTS.scala:81)|n	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)|n	at java.util.concurrent.FutureTask.run(FutureTask.java:266)|n	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)|n	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)|n	at java.lang.Thread.run(Thread.java:748)|n' timestamp='2018-09-27T11:11:10.081' nodeId='8']
`run` must run all pick-up requests even if the requests are more than the elevator number

**Comment by searler** [comment]
The elevators end up executing all the requests, but the final floor does not always match the floor specified in finalState. Seems that is still an acceptable test result

e.g.
`Vector(ElevatorState(15,Set()), ElevatorState(14,Set()))
`
`Vector(ElevatorState(1,Set()), ElevatorState(14,Set()))`

Is the scheduling expected to be deterministic so the same plan is executed on every test run?
If not, the test is over constrained.

**Comment by searler** [comment]
A trace that seems reasonable but violates the test condition
```
(0,ElevatorState(1,Set()))
(1,ElevatorState(7,Set(10, 13, 14)))
(0,ElevatorState(1,Set()))
(1,ElevatorState(8,Set(10, 13, 14)))
(0,ElevatorState(1,Set()))
(1,ElevatorState(9,Set(10, 13, 14)))
(0,ElevatorState(2,Set(7, 15))) // first elevator picked up request for 7
(1,ElevatorState(10,Set(13, 14)))
(0,ElevatorState(3,Set(7, 15)))
(1,ElevatorState(11,Set(13, 14)))
(0,ElevatorState(4,Set(7, 15)))
(1,ElevatorState(12,Set(13, 14)))
(0,ElevatorState(5,Set(7, 15)))
(1,ElevatorState(13,Set(14)))
(0,ElevatorState(6,Set(7, 15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(7,Set(15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(8,Set(15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(9,Set(15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(10,Set(15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(11,Set(15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(12,Set(15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(13,Set(15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(14,Set(15)))
(1,ElevatorState(14,Set()))
(0,ElevatorState(15,Set()))
(1,ElevatorState(14,Set()))
```

**Comment by searler** [comment]
The test contains a race condition: the new request is injected after the system has started running.

Elevator 1 has often moved past floor 7 on its way to floor  10 before the request is removed from queue.
At that point, elevator 1 is no longer a candidate.

Elevator 0 then becomes a candidate since it is stationary.

**Comment by wi101** [comment]
@searler Thanks for this issue, the elevators will be executed in a different fiber (they will be moved every 1 millisecond) and in parallel they checks the requests (in other fiber) (so the elevators was faster) it moved before consuming the request, we can increment the time to be more logic
(sorry for the late, I just saw you message)

**Comment by searler** [comment]
I no longer see test failures.

Thanks

**Comment by wi101** [comment]
Sounds great, I will merge the PR, 
@searler thanks again :)
